Non python lint fixes
RimSort/RimSort pull request #370
Opened 2024-05-25 19:30 UTC by hk21702

Linting fixes for non-python related things

2024-05-26 21:56 UTC, LionelColaso approved these changes
looks Good

2024-05-27 00:30 UTC, hk21702 commented
Will hold off on merging so @twstagg can take one last look over

2024-05-27 02:10 UTC, twstagg requested changes
Let's skip any changes to the update.sh, we are going to be removing this soon in favor of a dedicated updater module/program.

2024-05-27 04:59 UTC, twstagg approved these changes

2024-06-02 11:09 UTC, merged