[145] Implement "mod type filter"
RimSort/RimSort pull request #653
Opened 2024-10-18 05:14 UTC by LionelColaso

Add mod type filter that can filter a mod list by their:
* "C# mod icon" + Tooltip
* "XML mod icon" + Tooltip

Fixed Filter Mode now changes Icons by state:
* Icons as per state + Tooltip

2025-01-01 17:22 UTC, Patryk-Malinowski requested changes
In active modlist the tooltip for hide filter is incorrect and always says its disabled:
![image](https://github.com/user-attachments/assets/35598c4c-9fe1-448c-99d6-adecf582f432)

For the inactive modlist it always says its enabled:
![image](https://github.com/user-attachments/assets/f4ab8e47-174a-4910-b2b5-d99aacdfc905)

Also see comments

2025-01-01 18:30 UTC, LionelColaso commented on app/views/mods_panel.py
> +            source_index = self.inactive_data_source_filter_type_index
Sone

2025-01-01 18:31 UTC, Patryk-Malinowski commented
Oh also I just realized there is this option that hides the types next to each mod. We probably should make it so that if disabled it also hides the filter:
![image](https://github.com/user-attachments/assets/cc845e42-0417-4b45-a456-10e0bc78c641)


Hide the filter for mod types:
![image](https://github.com/user-attachments/assets/4390d4ab-5e54-41e1-b7d3-0bd2e92fedfa)

2025-01-01 18:32 UTC, LionelColaso commented on app/views/mods_panel.py
> +            source_index = self.inactive_data_source_filter_type_index
Done

2025-01-01 18:33 UTC, LionelColaso commented on app/views/mods_panel.py
> +    def connect_signals(self) -> None:
Done

2025-01-01 20:06 UTC, LionelColaso commented
> In active modlist the tooltip for hide filter is incorrect and always says its disabled: ![image](https://private-user-images.githubusercontent.com/145374860/399573535-35598c4c-9fe1-448c-99d6-adecf582f432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTczNTM1LTM1NTk4YzRjLTlmZTEtNDQ4Yy05OWQ2LWFkZWNmNTgyZjQzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmRhNWNkOTIzYzkxZTdkMmQ5MjI0ZmU0NjAzMGQ1ZTBiYzQ4ZjViZDU4YTNiYjFlMTZiNWJkNmY0OWRjZWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tGh7yDyA9iZ1dNi7Qu84jEz6uLk0rLg26giuAore7d0)
> 
> For the inactive modlist it always says its enabled: ![image](https://private-user-images.githubusercontent.com/145374860/399573618-f4ab8e47-174a-4910-b2b5-d99aacdfc905.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTczNjE4LWY0YWI4ZTQ3LTE3NGEtNDkxMC1iMmI1LWQ5OWFhY2RmYzkwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTE4ODJiOGZjZDE1MDVkNWY4M2UxNDU1NzQ1ZWFhMGE1ZGE1YjJjMTlmZjM5MDI2N2UwNjdmOWZlOTQ0ZTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GGI0_S2yDIP1rJK3bVq62NyQ5yBBMFGJdKazIes_JAQ)
> 
> Also see comments

Fixed now

2025-01-01 20:06 UTC, LionelColaso commented on app/views/mods_panel.py
> +            item.setData(Qt.ItemDataRole.UserRole, item_data)
Should not be an issue now

2025-01-01 20:11 UTC, LionelColaso commented
> Oh also I just realized there is this option that hides the types next to each mod. We probably should make it so that if disabled it also hides the filter: ![image](https://private-user-images.githubusercontent.com/145374860/399581263-cc845e42-0417-4b45-a456-10e0bc78c641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjYzLWNjODQ1ZTQyLTA0MTctNGI0NS1hNDU2LTEwZTBiYzc4YzY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjc3OGFlYjQ1MmUyNmEzMDZiY2Q3Y2RmNzc5N2Y3OTc4MDQ5MGQzMDc0ODYwYzE3ZTUwMzhlYWFkM2FlMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._WZflsylhPuuGP0_Q_hzYwXGbzT-jZF609UkoxdBjZM)
> 
> Hide the filter for mod types: ![image](https://private-user-images.githubusercontent.com/145374860/399581295-4390d4ab-5e54-41e1-b7d3-0bd2e92fedfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjk1LTQzOTBkNGFiLTVlNTQtNDFlMS1iN2QzLTBiZDJlOTJmZWRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGE3MDg5ODQ2YWIzMjI1NTVkZTAxYTZmNThkMDI2NzI5MzlmZjkxYTM2YWY3ZTUxNTQ3YzUxMWFmNzc2ZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1sEd57QNNu-dJeQ324DwLX0_eHp_biR_j5tH5xktKgE)

Not Sure if hiding filters is necessary since it would be confusing for users

2025-01-01 22:03 UTC, Patryk-Malinowski commented
> > Oh also I just realized there is this option that hides the types next to each mod. We probably should make it so that if disabled it also hides the filter: ![image](https://private-user-images.githubusercontent.com/145374860/399581263-cc845e42-0417-4b45-a456-10e0bc78c641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjYzLWNjODQ1ZTQyLTA0MTctNGI0NS1hNDU2LTEwZTBiYzc4YzY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjc3OGFlYjQ1MmUyNmEzMDZiY2Q3Y2RmNzc5N2Y3OTc4MDQ5MGQzMDc0ODYwYzE3ZTUwMzhlYWFkM2FlMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._WZflsylhPuuGP0_Q_hzYwXGbzT-jZF609UkoxdBjZM)
> > Hide the filter for mod types: ![image](https://private-user-images.githubusercontent.com/145374860/399581295-4390d4ab-5e54-41e1-b7d3-0bd2e92fedfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjk1LTQzOTBkNGFiLTVlNTQtNDFlMS1iN2QzLTBiZDJlOTJmZWRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGE3MDg5ODQ2YWIzMjI1NTVkZTAxYTZmNThkMDI2NzI5MzlmZjkxYTM2YWY3ZTUxNTQ3YzUxMWFmNzc2ZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1sEd57QNNu-dJeQ324DwLX0_eHp_biR_j5tH5xktKgE)
> 
> Not Sure if hiding filters is necessary since it would be confusing for users

Should we remove the settings option so? Or is that option supposed to only refer to the icons next to the mod items, then maybe renaming it?

2025-01-01 22:13 UTC, LionelColaso commented
> > > Oh also I just realized there is this option that hides the types next to each mod. We probably should make it so that if disabled it also hides the filter: ![image](https://private-user-images.githubusercontent.com/145374860/399581263-cc845e42-0417-4b45-a456-10e0bc78c641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjYzLWNjODQ1ZTQyLTA0MTctNGI0NS1hNDU2LTEwZTBiYzc4YzY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjc3OGFlYjQ1MmUyNmEzMDZiY2Q3Y2RmNzc5N2Y3OTc4MDQ5MGQzMDc0ODYwYzE3ZTUwMzhlYWFkM2FlMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._WZflsylhPuuGP0_Q_hzYwXGbzT-jZF609UkoxdBjZM)
> > > Hide the filter for mod types: ![image](https://private-user-images.githubusercontent.com/145374860/399581295-4390d4ab-5e54-41e1-b7d3-0bd2e92fedfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjk1LTQzOTBkNGFiLTVlNTQtNDFlMS1iN2QzLTBiZDJlOTJmZWRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGE3MDg5ODQ2YWIzMjI1NTVkZTAxYTZmNThkMDI2NzI5MzlmZjkxYTM2YWY3ZTUxNTQ3YzUxMWFmNzc2ZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1sEd57QNNu-dJeQ324DwLX0_eHp_biR_j5tH5xktKgE)
> > 
> > 
> > Not Sure if hiding filters is necessary since it would be confusing for users
> 
> Should we remove the settings option so? Or is that option supposed to only refer to the icons next to the mod items, then maybe renaming it?

I am not sure if it was for anything else other than hiding icons
https://discord.com/channels/1120855389651599400/1120855390138142782/1171584564137824286

![image](https://github.com/user-attachments/assets/b0066587-0827-4199-a706-e992f36cbf08)

2025-01-01 22:15 UTC, Patryk-Malinowski approved these changes
lgtm

2025-01-01 22:16 UTC, merged

2025-01-01 22:17 UTC, Patryk-Malinowski commented
> > > > Oh also I just realized there is this option that hides the types next to each mod. We probably should make it so that if disabled it also hides the filter: ![image](https://private-user-images.githubusercontent.com/145374860/399581263-cc845e42-0417-4b45-a456-10e0bc78c641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjYzLWNjODQ1ZTQyLTA0MTctNGI0NS1hNDU2LTEwZTBiYzc4YzY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjc3OGFlYjQ1MmUyNmEzMDZiY2Q3Y2RmNzc5N2Y3OTc4MDQ5MGQzMDc0ODYwYzE3ZTUwMzhlYWFkM2FlMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._WZflsylhPuuGP0_Q_hzYwXGbzT-jZF609UkoxdBjZM)
> > > > Hide the filter for mod types: ![image](https://private-user-images.githubusercontent.com/145374860/399581295-4390d4ab-5e54-41e1-b7d3-0bd2e92fedfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjk1LTQzOTBkNGFiLTVlNTQtNDFlMS1iN2QzLTBiZDJlOTJmZWRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGE3MDg5ODQ2YWIzMjI1NTVkZTAxYTZmNThkMDI2NzI5MzlmZjkxYTM2YWY3ZTUxNTQ3YzUxMWFmNzc2ZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1sEd57QNNu-dJeQ324DwLX0_eHp_biR_j5tH5xktKgE)
> > > 
> > > 
> > > Not Sure if hiding filters is necessary since it would be confusing for users
> > 
> > 
> > Should we remove the settings option so? Or is that option supposed to only refer to the icons next to the mod items, then maybe renaming it?
> 
> I am not sure if it was for anything else other than hiding icons https://discord.com/channels/1120855389651599400/1120855390138142782/1171584564137824286
> 
> ![image](https://private-user-images.githubusercontent.com/2488703/399590251-b0066587-0827-4199-a706-e992f36cbf08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NzAwMzMsIm5iZiI6MTczNTc2OTczMywicGF0aCI6Ii8yNDg4NzAzLzM5OTU5MDI1MS1iMDA2NjU4Ny0wODI3LTQxOTktYTcwNi1lOTkyZjM2Y2JmMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDFUMjIxNTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM0MjUyN2YwNTkxNjVmNWIzYmFkOTg4YzZlNmE3MjcyNGY0OGM4ZTg5N2RmM2E3ZmE2MWExNDM1MGZlMzA0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0XApj0FIXHdLSOylZ864gtUdupQgfxcGLmh9yTn-ur8)

Twsta does mention it would be for an actual filter implementation. So in my mind it would make sense to also hide that filter, especially since its on by default the user could turn it off if they dont care about c#/xml stuff? I'll leave it up to you.

2025-01-01 22:24 UTC, LionelColaso commented
> > > > > Oh also I just realized there is this option that hides the types next to each mod. We probably should make it so that if disabled it also hides the filter: ![image](https://private-user-images.githubusercontent.com/145374860/399581263-cc845e42-0417-4b45-a456-10e0bc78c641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjYzLWNjODQ1ZTQyLTA0MTctNGI0NS1hNDU2LTEwZTBiYzc4YzY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjc3OGFlYjQ1MmUyNmEzMDZiY2Q3Y2RmNzc5N2Y3OTc4MDQ5MGQzMDc0ODYwYzE3ZTUwMzhlYWFkM2FlMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._WZflsylhPuuGP0_Q_hzYwXGbzT-jZF609UkoxdBjZM)
> > > > > Hide the filter for mod types: ![image](https://private-user-images.githubusercontent.com/145374860/399581295-4390d4ab-5e54-41e1-b7d3-0bd2e92fedfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NjIyMDUsIm5iZiI6MTczNTc2MTkwNSwicGF0aCI6Ii8xNDUzNzQ4NjAvMzk5NTgxMjk1LTQzOTBkNGFiLTVlNTQtNDFlMS1iN2QzLTBiZDJlOTJmZWRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQyMDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGE3MDg5ODQ2YWIzMjI1NTVkZTAxYTZmNThkMDI2NzI5MzlmZjkxYTM2YWY3ZTUxNTQ3YzUxMWFmNzc2ZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1sEd57QNNu-dJeQ324DwLX0_eHp_biR_j5tH5xktKgE)
> > > > 
> > > > 
> > > > Not Sure if hiding filters is necessary since it would be confusing for users
> > > 
> > > 
> > > Should we remove the settings option so? Or is that option supposed to only refer to the icons next to the mod items, then maybe renaming it?
> > 
> > 
> > I am not sure if it was for anything else other than hiding icons https://discord.com/channels/1120855389651599400/1120855390138142782/1171584564137824286
> > ![image](https://private-user-images.githubusercontent.com/2488703/399590251-b0066587-0827-4199-a706-e992f36cbf08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NzAwMzMsIm5iZiI6MTczNTc2OTczMywicGF0aCI6Ii8yNDg4NzAzLzM5OTU5MDI1MS1iMDA2NjU4Ny0wODI3LTQxOTktYTcwNi1lOTkyZjM2Y2JmMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDFUMjIxNTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM0MjUyN2YwNTkxNjVmNWIzYmFkOTg4YzZlNmE3MjcyNGY0OGM4ZTg5N2RmM2E3ZmE2MWExNDM1MGZlMzA0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0XApj0FIXHdLSOylZ864gtUdupQgfxcGLmh9yTn-ur8)
> 
> Twsta does mention it would be for an actual filter implementation. So in my mind it would make sense to also hide that filter, especially since its on by default the user could turn it off if they dont care about c#/xml stuff? I'll leave it up to you.

I am ok with the toggle to hide it as well, just not by default though
or it could be another toggle for example "enable mod filter by types"

2025-01-01 23:20 UTC, Patryk-Malinowski commented
Oh yeah not by default sorry if I made it seem like I wanted it hidden by default. I think the one checkbox would be enough and if its enabled we show the filter option and the icons next to each mod, otherwise hide both. And leave it on by default

2025-01-02 19:57 UTC, LionelColaso commented
> Oh yeah not by default sorry if I made it seem like I wanted it hidden by default. I think the one checkbox would be enough and if its enabled we show the filter option and the icons next to each mod, otherwise hide both. And leave it on by default

ok so #731 is the solution